name: Build the app

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@v1.0.5

    - name: Decrypt the keystore for signing
      run: |
        echo "${{ secrets.KEYSTORE_ENCRYPTED }}" > keystore.asc
        gpg -d --passphrase "${{ secrets.KEYSTORE_PASSWORD }}" --batch keystore.asc > keystore.jks

    - name: Build Release APK
      run: ./gradlew assembleRelease

    - name: Upload Release arm64-v8a APK
      uses: actions/upload-artifact@v3
      with:
          name: ark-shelf-arm64-v8a-apk
          path: ./app/build/outputs/apk/release/ark-shelf-arm64-v8a-release.apk

    - name: Upload Release armeabi-v7a APK
      uses: actions/upload-artifact@v3
      with:
          name: ark-shelf-armeabi-v7a-apk
          path: ./app/build/outputs/apk/release/ark-shelf-armeabi-v7a-release.apk

    - name: Upload Release universal APK
      uses: actions/upload-artifact@v3
      with:
          name: ark-shelf-universal-apk
          path: ./app/build/outputs/apk/release/ark-shelf-universal-release.apk
