name: Build the app

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@v1.0.5

    - name: Build Debug APK
      run: ./gradlew assembleDebug

    - name: Build Release APK
      run: ./gradlew assembleRelease

    - name: Upload Debug APK
      uses: actions/upload-artifact@v3
      with:
        name: ark-shelf-debug
        path: ./app/build/outputs/apk/debug/ark-shelf-debug.apk

    - name: Upload Release APK
      uses: actions/upload-artifact@v3
      with:
        name: ark-shelf-release
        path: ./app/build/outputs/apk/release/ark-shelf-release.apk

 
